### ISSUE TITLE
Warning : Tratamento de erro para tags não localizadas

### ISSUE THREAD

**Issue by jorgesallum** [scielo-edo/jats2tex#7]
# Vídeo
https://www.youtube.com/watch?v=yQEjJMqk-2g
# Demanda inicial
Caso o conversor localize tags não mapeadas no xd, converter para comando de bloco ou linha mas em comentário. 

Ex:

`<elefante>XXX</elefante>`

```
%\elefante{XXX}
```

**Comment by yamadapc** [comment]
Flag `-W`

**Comment by jorgesallum** [comment]
Como salvar o log? Tá extremamente difícil gerenciar a saída. Tentei com  bash+less, com >> log, mas não consegui.
